#!/usr/bin/env python3
"""Compare each mapped unit's area with the area printed in 1931 Table I.
Needs shapely. Equal-area (sinusoidal) computation on data/units1931.geojson."""
import json, math, os
from shapely.geometry import shape
from shapely.ops import transform
HERE = os.path.dirname(os.path.abspath(__file__))
T = json.load(open(os.path.join(HERE, '..', 'source', 'reference', 'table1_area_sq_miles.json')))
G = json.load(open(os.path.join(HERE, '..', 'data', 'units1931.geojson')))
R = 6371.0088
def sinu(x, y, z=None):
    return R * math.radians(x) * math.cos(math.radians(y)), R * math.radians(y)
KM2_PER_SQMI = 2.589988
names = {}
rows = []
for f in G['features']:
    k = f['properties']['code']
    a = transform(sinu, shape(f['geometry'])).area / KM2_PER_SQMI
    t = T.get(k)
    rows.append((k, round(a), t, (a / t - 1) * 100 if t else None))
tot = sum(r[1] for r in rows if not r[0].startswith('x_'))
for k, a, t, d in rows:
    flag = '' if d is None else ('  <<<' if abs(d) > 25 else ('  <' if abs(d) > 10 else ''))
    print(f'{k:>8} map {a:>9,}  printed {t if t else "-":>9}  diff {"" if d is None else f"{d:+6.1f}%"}{flag}')
print(f'mapped total {tot:,} vs printed INDIA {T["INDIA"]:,} ({(tot / T["INDIA"] - 1) * 100:+.1f}%)')

out = [{'code': k, 'map': a, 'printed': t, 'diff': None if d is None else round(d, 1)} for k, a, t, d in rows]
with open(os.path.join(HERE, '..', 'data', 'areas.js'), 'w') as fh:
    fh.write('/* Generated by tools/area_check.py: mapped area vs Table I (sq. miles) */\nwindow.AREAS = ' +
             json.dumps({'rows': out, 'total': tot, 'india': T['INDIA']}) + ';\n')
