#!/usr/bin/env python3
"""Fold the transcription of Table XV Part II (Bilingualism), source/transcribed_bilingual/pNNN.json,
into data/bilingual.js and data/bilingual.csv, linked to the Part I classification in data/census.js.
Figures are kept as printed; entries whose subsidiary counts do not add up to column 3 are flagged."""
import csv, glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'source', 'transcribed_bilingual')
OUT = os.path.join(HERE, '..', 'data')

cs = open(os.path.join(OUT, 'census.js')).read()
C = json.loads(cs[cs.index('{'):cs.rindex('}') + 1])
L = C['langs']

AREA = {'Bengal': '5', 'Bombay': '7', 'Sikkim': '33', 'Madras': '12', 'Cochin': '27a', 'Bihar and Orissa': '6',
        'Hyderabad': '25', 'Punjab': '14', 'Travancore': '27b', 'Mysore': '28', 'Central India Agency': '22',
        'Baluchistan': '4', 'North-West Frontier Province': '13', 'Central Provinces and Berar': '9',
        'Central Provinces': '9', 'Jammu and Kashmir': '26', 'Baroda': '18', 'Assam': '3', 'Burma': '8',
        'Coorg': '10', 'Rajputana Agency': '32', 'Delhi': '11', 'Gwalior': '24',
        'Western India States Agency': '35', 'United Provinces': '15'}

# mother tongue as printed in Part II -> node name in Part I (section A)
MT = {'Punjabi': 'Panjabi', 'Savara': 'Sawara', 'Mro': 'Mro (Mru)', 'Bhotia': 'Tibetan Group'}

# subsidiary-language spelling variants -> one name for aggregation (printed form is kept too)
SUB = {'Tibeto-Burmese languages': 'Tibeto-Burmese Languages', 'Mon Khmer Group': 'Mon-Khmer Group',
       'Saurasthri': 'Saurashtri', 'Western Hind.': 'Western Hindi', 'Bengal': 'Bengali',
       'Kurukh': 'Kurukh or Oraon', 'Coorgi': 'Kodagu or Coorgi', 'Ahirani': 'Ahirani or Khandeshi',
       'Khandeshi': 'Ahirani or Khandeshi', 'Siraiki': 'Siraiki or Jatki', 'Thareli': 'Thareli or Dhatki',
       'Other Tibeto Burman Languages': 'Other Tibeto-Burman languages',
       'Other Tibeto-Burmese Groups': 'Other Tibeto-Burman languages', 'Kandhi': 'Kandhi or Kui',
       'Punjabi': 'Panjabi'}

def norm(s):
    return re.sub(r'[^a-z]', '', s.lower())
A_nodes = [l for l in L if L[0] and l['name'] and True]
section_a = [l for l in L if l['id'] != 0 and (lambda p: p)(l)]
def root_of(l):
    while l['parent'] is not None:
        l = L[l['parent']]
    return l['name']
byname = {}
for l in L:
    if root_of(l).startswith('A.'):
        byname.setdefault(norm(l['name']), l)
def find(name):
    n = norm(MT.get(name, name))
    if n in byname:
        return byname[n]
    for k, l in byname.items():
        if k.startswith(n) or n.startswith(k) and len(k) > 4:
            return l
    return None

entries = []
for f in sorted(glob.glob(os.path.join(SRC, 'p*.json'))):
    d = json.load(open(f))
    for e in d['entries']:
        node = find(e['mother_tongue'])
        subs = []
        for s in e['subsidiary']:
            name, n = s[0], s[1]
            subs.append({'name': name, 'as': SUB.get(name, name), 'n': n if isinstance(n, int) else None,
                         'illegible': not isinstance(n, int)})
        tot = sum(s['n'] or 0 for s in subs)
        bil = e['bilingual'] if isinstance(e['bilingual'], int) else None
        entries.append({
            'num': e['num'], 'mt': e['mother_tongue'], 'sub_of': e.get('sub_of'),
            'lang': node['id'] if node else None,
            'areas': e['areas'], 'units': [AREA.get(a) for a in e['areas']],
            'total': e['total_speakers'], 'bilingual': bil, 'sum': tot,
            'diff': None if bil is None else tot - bil,
            'subs': subs, 'note': e.get('notes') or None, 'leaf': d['leaf'], 'page': d['printed_page']})
        if not node:
            print('no Part I match for', e['mother_tongue'], file=sys.stderr)
        for a in e['areas']:
            if a not in AREA:
                print('unknown area', a, file=sys.stderr)

with open(os.path.join(OUT, 'bilingual.js'), 'w') as fh:
    fh.write('/* Generated by tools/build_bilingual.py from source/transcribed_bilingual/.\n'
             '   Census of India 1931, Vol. I Part II, Table XV Part II (Bilingualism), pp. 510-512. */\n')
    fh.write('window.BILINGUAL = ' + json.dumps(entries, ensure_ascii=False, separators=(',', ':')) + ';\n')
with open(os.path.join(OUT, 'bilingual.csv'), 'w', newline='') as fh:
    w = csv.writer(fh)
    w.writerow(['entry', 'mother_tongue', 'areas_returned_from', 'total_speakers', 'returned_bilingual_col3',
                'subsidiary_language_printed', 'subsidiary_language', 'persons', 'printed_page', 'scan_leaf'])
    for e in entries:
        for s in e['subs']:
            w.writerow([e['num'] or '', e['mt'], '; '.join(e['areas']), e['total'], e['bilingual'],
                        s['name'], s['as'], s['n'] if s['n'] is not None else '?', e['page'], e['leaf']])
bad = [e for e in entries if e['diff']]
print(f'{len(entries)} entries; {len(bad)} do not add up to column 3 in the print', file=sys.stderr)
